### ISSUE TITLE
mkl-fft dependency cannot be satisfied

### ISSUE THREAD

**Issue by akfranco** [harshitcodes/momentum_trading_testing#2]
After creating a virtual environment with `python3 -m venv .venv/` and installing from the requirements.txt with `pip install -r requirements.txt`, the end of the process results in this:

`Collecting mkl-fft==1.0.6 (from -r requirements.txt (line 27))
  Could not find a version that satisfies the requirement mkl-fft==1.0.6 (from -r requirements.txt (line 27)) (from versions: )
No matching distribution found for mkl-fft==1.0.6 (from -r requirements.txt (line 27))`

How should I proceed?

**Comment by nguyenhieuec** [comment]
Please check the python version using to create venv. May be downgrade your python will helpful.
